# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReduxFormExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReduxFormExample

  target 'ReduxFormExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReduxFormExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReduxFormExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReduxFormExample-tvOS

end
